# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e922575435df8686b4eac1c8da18cad7"
name = "checkout-upsell"
application_url = "https://mario-leg-fourth-thus.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mehul-checkout-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mario-leg-fourth-thus.trycloudflare.com/auth/callback",
  "https://mario-leg-fourth-thus.trycloudflare.com/auth/shopify/callback",
  "https://mario-leg-fourth-thus.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
